.github/PULL_REQUEST_TEMPLATE.md
package-lock.json
package.json

Added pull request template which is significant for contributors.

feature(#9): add pull request template

---

CHANGELOG.md
README.md
package.json
src/index.ts

Published the package for v0.0.8
-   [X] Other

release(v0.0.8): release version 0.0.8

---

.github/COMMIT_CONVENTION.md
CONTRIBUTING.md
package.json

- Updated commit convention.
- Updated the PR guidelines in contribution guidelines.
- Updated `pre-commit` command to run `npm run verify`.
-   [X] Other
-   [ ] …

docs(dev): update commit convention (#21)

---

.prettierignore
CONTRIBUTING.md
package-lock.json
package.json
src/functions/GenerateComponent.test.ts
src/functions/GenerateComponent.ts
src/helpers/checkProperty.test.ts
src/helpers/checkProperty.ts
src/helpers/checkReact.test.ts
src/helpers/checkReact.ts
src/helpers/getRootPath.test.ts
src/helpers/getRootPath.ts
src/mocks/mock.package.json
src/template/Component.test.ts
src/template/Component.ts
src/template/Test.test.ts
src/template/Test.ts
tsconfig.json
vitest.config.ts

- Added `vitest` support to the project.
- Added unit test for all existing modules.
- Added new test commands in `package.json`.
- Updated `.prettierignore`.
- Update **contribution guidelines**.
-   [X] Other
-   [X] Provide a description in this PR that addresses **what** the PR is solving, or reference …

test(core): add unit test for all the modules (#8)

---

package-lock.json
package.json

Fixed the module not found error while running the command
-   [ ] Other

fix(deps): move required deps to dependencies (#27)

---

src/template/Component.ts

- removed additional '.' from component template
-   [ ] Other

fix(template): remove extra '.' from component template (#36)

---

src/functions/GenerateComponent.test.ts
src/functions/GenerateComponent.ts
src/helpers/getConfig.test.ts
src/helpers/getConfig.ts
src/mocks/arclix.config.json
src/template/Component.test.ts

- added appropriate tests for `config` feature
-   [X] New Feature
-   [ ] Other

test(config): add tests for generate config feature (#43)

---

package.json
src/functions/GenerateConfigFile.ts
src/index.ts
src/types/enum.ts

- added separate command to generate config file to existing react project.
```bash
npx arclix init
```
-   [X] New Feature
-   [ ] Other
-   [X] Ideally, include relevant tests that …

feat(config): create a command to generate config file (#48)

---

CHANGELOG.md
package.json
src/index.ts

Released version 0.1.1 with following features:
- Configure `arclix` for genreate component using `arclix.config.json`
- New `command` to generate `arclix.config.json` to existing project
-   [X] Other
-   [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue …

chore(release)!: release v0.1.1

---

commitlint.config.cjs

- Added `release` by overriding `type-enums` in commitlint config
-   [X] Other

chore(commitlint): add release to type-enum in config (#55)

---

src/tests/generateComponent.test.ts

- fixed formatting in `generateComponent.tests.ts` file
-   [X] Other

chore(lint): fix format in generateComponent test file caused by (#63)

---

.github/workflows/ci.yml
.prettierignore

As a member of the development team, I am proposing to add pipelines to our Arclix project to automate the testing and deployment processes. This will improve our development workflow and make it easier for us to maintain the project.
The proposed pipelines will include a continuous integration (CI) pipeline to automatically build and test the code whenever changes are pushed to the repository.
---
-   [X] Other
- …

ci: add ci workflow to verify PR (#54)

---

src/generate/helpers/getPackageFile.ts
src/tests/generateComponent.test.ts
src/tests/getPackageFile.test.ts
vitest.config.ts

- added coverage `threshold` to the unit tests in `vitest.config.ts`
-   [X] Other

test: add coverage threshold to unit tests (#67)

---

src/create/CreateProject.ts
src/create/GenerateConfigFile.ts
src/generate/GenerateComponent.ts
src/generate/GenerateComponentUtility.ts
src/generate/helpers/checkProperty.ts
src/generate/helpers/checkReact.ts
src/generate/helpers/getConfig.ts
src/generate/helpers/getPackageFile.ts
src/generate/helpers/getRootPath.ts
src/generate/templates/component.ts
src/tests/checkProperty.test.ts
src/tests/checkReact.test.ts
src/tests/generateComponent.test.ts
src/tests/getPackageFile.test.ts
src/tests/getRootPath.test.ts
src/types/type.ts

- Refactored create and generate modules of the core functionality
-   [X] Other

refactor(core): update create and generate cli functionality

---

CHANGELOG.md
package-lock.json
package.json
src/index.ts

- Released package version 0.1.2
-   [X] Other

release: v0.1.2

---

CHANGELOG.md

-  Fixed typo in `changelog` date for the release v0.1.2.
-   [X] Other

fix: typo in changelog date

---

src/generate/GenerateComponent.ts
src/generate/GenerateComponentUtility.ts
src/tests/generateComponent.test.ts

- Fixed overriding existing component by adding additional check for checking component before generating
-   [ ] Other
-   [X] Ideally, include relevant tests that …

fix(generate): add component exist check before generation (#78)

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/index.ts

- Released package version 0.1.3.
- For more info refer  [CHANGELOG](https://github.com/arclix/core/blob/master/CHANGELOG.md).
-   [X] Other
-   [X] Ideally, include …

release: v0.1.3

---

src/generate/templates/component.ts
src/generate/templates/test.ts
src/tests/componentTemplate.test.ts
src/tests/testTemplate.test.ts

- Updated component and test templates to be generic.
- Updated the tests for both component and test.
-   [X] New Feature
-   [ ] Other
-   [X] Ideally, include relevant tests that fail …

feat: update component and test templates to be generic (#90)

---

.github/workflows/cd.yml

I write a yaml workflow to automatically publish the package on NPM registry, whenever new release is created.
-   [X] New Feature
-   [ ] Other
-   [X] Ideally, include relevant tests …

ci: workflow to publish on npm registery  (#71)

---

CHANGELOG.md
package-lock.json
package.json

- Releasing package version v0.1.4
-   [X] Other

release: v0.1.4

---

.github/workflows/cd.yml

- Fixed invalid build command in publish workflow
- Fixes #94 
-   [ ] Other

fix(ci): invalid build command

---

CHANGELOG.md

- Updated the changelog for arclix v0.1.4
-   [X] Other

chore(changelog): update changelog for v0.1.4

---

CHANGELOG.md

- Fixed the indentation issue in changelog.
-   [ ] Other

chore: fix indentaion in changelog

---

README.md

- Updated the `readme` file with updated contents and link.

chore: update readme file with updated links

---

CHANGELOG.md
package-lock.json
package.json
src/index.ts

- Release arclix version `0.1.5`, check [CHANGELOG](https://github.com/arclix/core/blob/master/CHANGELOG.md) for more information.

release: v0.1.5

---

README.md

- Updated the links to website in readme file to latest.

chore(readme): update the links in readme to latest

---

.github/workflows/ci.yml

- Updated the target branch from `master` to `main` for checking pull request

ci: update the target branch to main
